#!/usr/bin/env node
// fleet-map.mjs — regenerate the canonical fleet source-of-truth map from the
// ollama_proxy DB (the system that already polls every endpoint). Pure read (SELECT only).
// Uses the porsager `postgres` driver already vendored in this repo.
// Usage: DATABASE_URL=postgresql://...@localhost:5434/ollama_fleet node scripts/fleet-map.mjs > fleet-map.md
import postgres from "postgres";

const sql = postgres(process.env.DATABASE_URL, { ssl: false, idle_timeout: 5, max: 1 });

const rows = await sql`
  SELECT s.name, s.host, s.backend_type,
         snap.available_models, snap.polled_at
  FROM servers s
  LEFT JOIN LATERAL (
    SELECT available_models, polled_at
    FROM server_snapshots
    WHERE server_id = s.id
    ORDER BY polled_at DESC
    LIMIT 1
  ) snap ON true
  ORDER BY s.host;
`;
await sql.end();

const now = new Date().toISOString();
let md = `# Fleet map (AUTO-GENERATED — do not edit by hand)\n\n`;
md += `> Source: ollama_proxy DB (\`servers\` + latest \`server_snapshots\`). Regenerated by\n`;
md += `> \`ollama_proxy/scripts/fleet-map.mjs\`. Last run: ${now}\n\n`;
md += `| Endpoint | Host | Runtime | Model(s) | Last polled |\n|---|---|---|---|---|\n`;
for (const r of rows) {
  const am = Array.isArray(r.available_models) ? r.available_models : [];
  const models = am.map((m) => (typeof m === "string" ? m : (m.name ?? m.id ?? m.model)))
                   .filter(Boolean).join(", ") || "(none / unreachable)";
  const runtime = r.backend_type === "vllm" ? "vLLM"
                : r.backend_type === "ollama" ? "Ollama" : (r.backend_type ?? "?");
  const polled = r.polled_at ? new Date(r.polled_at).toISOString() : "never";
  md += `| \`${r.host}\` | ${r.name} | ${runtime} | ${models} | ${polled} |\n`;
}
process.stdout.write(md);
